In [1]:
# 1. Write a Python Program to Add Two Matrices?

# Sol :

import numpy as np

a = np.matrix([[1,2,3], [4,5,6], [7,8,9]])

b = np.matrix([[3,4,5], [6,7,8],[9, 10, 11]])

print(f"The addition of two matrices a and b is : \n{a+b}")

The addition of two matrices a and b is : 
[[ 4  6  8]
 [10 12 14]
 [16 18 20]]


In [2]:
# 2. Write a Python Program to Multiply Two Matrices?

# Sol :

import numpy as np

a = np.matrix([[1,2,3], [4,5,6], [7,8,9]])

b = np.matrix([[3,4,5], [6,7,8],[9,10,11]])

print(f"The multiplication of a and b is : \n{a*b}")

The multiplication of a and b is : 
[[ 42  48  54]
 [ 96 111 126]
 [150 174 198]]


In [3]:
# 3. Write a Python Program to Transpose a Matrix?

# Sol : 

import numpy as np

a = np.matrix([[1,2,3], [4,5,6], [7,8,9]])

print(f"The transpose of \n{a} is : \n\n{a.T}")

The transpose of 
[[1 2 3]
 [4 5 6]
 [7 8 9]] is : 

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [4]:
# 4. Write a Python Program to Sort Words in Alphabetic Order

# Sol :

def char():
    try:
        char = input("Enter the string : ")
        char1 = ""
        k = char.lower().split()
        k.sort()
        print("After sorting the words : ")
        for i in k:
            print("\t\t", i)
    except Exception as e:
        print("The Error has occured")
        print(f"The error is {e}")

In [5]:
char()

Enter the string : My dad is my hero
After sorting the words : 
		 dad
		 hero
		 is
		 my
		 my


In [6]:
# 5. Write a Python Program to Remove Punctuation From a String?

# Sol : 

#     First we have to define the punctuations

punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

char = input("Enter the string : ")

char1 = ""

for i in char:
    if i not in punctuations:
        char1 += i
print(char1)

Enter the string : Hello!!!, he said ---and went
Hello he said and went
